### ISSUE TITLE
Hello, Im having this error

### ISSUE THREAD

**Issue by userbox020** [MatheusVp2/hCaptcha-Solver-MR#4]
devices not set
Traceback (most recent call last):
  File "hcaptcha.py", line 305, in <module>
    resolver = hCaptcha( '51829642-2cda-4b09-896c-594f89d700cc', 'democaptcha.com' )
  File "hcaptcha.py", line 79, in __init__
    self.__detector.loadModel(detection_speed="flash")
  File "C:\Users\Admin\Desktop\hcap\hCaptcha-Solver-MR-main\hcapmc\lib\site-packages\imageai\Detection\__init__.py", line 195, in loadModel
    model.load_weights(self.modelPath)
  File "C:\Users\Admin\Desktop\hcap\hCaptcha-Solver-MR-main\hcapmc\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2227, in load_weights
    with h5py.File(filepath, 'r') as f:
  File "C:\Users\Admin\Desktop\hcap\hCaptcha-Solver-MR-main\hcapmc\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "C:\Users\Admin\Desktop\hcap\hCaptcha-Solver-MR-main\hcapmc\lib\site-packages\h5py\_hl\files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'yolo.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by userbox020** [comment]
Hello, I downloaded the yolo.h5 from here:
https://github.com/OlafenwaMoses/ImageAI/releases/download/1.0/yolo.h5

but now im getting this other error:
devices not set
[ERRO] Houve algum erro ao requisitar o payload das imagens
[TIME] Finish: 4

**Comment by roralsorom** [comment]
same
